#!/bin/bash
# postinstall script for patching AppleRTC to prevent CMOS reset on Mountain Lion
# credit to oldnapalm for posting
# Copyright (C) tonymacx86 LLC

perl -pi -e 's|\x75\x2e\x0f\xb6|\xeb\x2e\x0f\xb6|' "${3}/System/Library/Extensions/AppleRTC.kext/Contents/MacOS/AppleRTC"

touch "${3}/System/Library/Extensions/"

exit 0
