#!/usr/bin/python
#
# Script to add DropSSDT=Yes for Chameleon boot loaders
#
# Copyright (C) tonymacx86 LLC

import sys
import os

vol = str(sys.argv[1])
boot = "/Extra/org.chameleon.Boot.plist"
plist = vol + boot
infile = open(plist, "r")
# check if DropSSDT has been written or not
DropSSDTCheck = False

body = ""

for line in infile:
    # if DropSSDT is there, advance the next line to
    # read past it, and then add the Yes string
    if "<key>DropSSDT</key>" in line:
        line = infile.next()
        line = "        <key>DropSSDT</key>\n"
        line += "        <string>Yes</string>\n"
        DropSSDTCheck = True
        
    # if we finish the tags and haven't written DropSSDT yet
    if "</dict>" in line and DropSSDTCheck == False:
        line = "        <key>DropSSDT</key>\n"
        line += "        <string>Yes</string>\n"
        line += "</dict>\n"
        DropSSDTCheck = True
        
    body += line
    
infile.close()

outfile = open(plist, "w")
outfile.write(body)
outfile.close()