pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./3-way_merge_concepts.html","3-way Merge Concepts","3-way Merge Concepts A merge session helps you combine separate sets of changes into a new version of the data, accommodating both sets of changes...",""],
["./archive_files.html","Archive Files","Archive Files Archives are files that contain other files, such as .zip. Beyond Compare displays them as folders, with a zipper icon, but by defau...",""],
["./bcclipmain.html","Clipboard Compare Overview","Clipboard Compare Overview Clipboard Compare runs in the background, keeping track of every time the Windows clipboard is updated with text. It ap...",""],
["./bcclipoptions.html","Clipboard Compare Options","Clipboard Compare Options These options control the behavior of Clipboard Compare. Run on Windows startup Automatically runs Clipboard Compare whe...",""],
["./calling_bc_from_other_applications.html","Calling Beyond Compare from Other Applications","Calling Beyond Compare from Other Applications As you would expect, Beyond Compare&#39;s setup program creates shortcuts to the main executable file, ...",""],
["./commandsbc.html","Common Commands","Common Commands The main menu changes depending on what kind of view is active. However, the commands listed below are common across different vie...",""],
["./commandsdata.html","Table Compare Commands","Table Compare Commands Following is a description of the Table Compare commands, in addition to the common commands . Most of these commands are a...",""],
["./commandsdir.html","Folder Compare Commands","Folder Compare Commands Following is a description of the Folder Compare commands, in addition to the common commands . Most of these commands are...",""],
["./commandsdirmerge.html","Folder Merge Commands","Folder Merge Commands Following is a description of the Folder Merge commands, in addition to the common commands . Most of these commands are ava...",""],
["./commandsdirsync.html","Folder Sync Commands","Folder Sync Commands Following is a description of the Folder Sync commands, in addition to the common commands . Most of these commands are avail...",""],
["./commandshex.html","Hex Compare Commands","Hex Compare Commands Following is a description of the Hex Compare commands, in addition to the common commands . Most of these commands are avail...",""],
["./commandshome.html","Home Commands","Home Commands Following is a description of the Home commands, in addition to the common commands . Pick Tools Options and switch to the Toolbars,...",""],
["./commandsmp3.html","MP3 Compare Commands","MP3 Compare Commands Following is a description of the MP3 Compare commands, in addition to the common commands . Most of these commands are avail...",""],
["./commandspix.html","Picture Compare Commands","Picture Compare Commands Following is a description of the Picture Compare commands, in addition to the common commands . Most of these commands a...",""],
["./commandsreg.html","Registry Compare Commands","Registry Compare Commands Following is a description of the Registry Compare commands, in addition to the common commands . Most of these commands...",""],
["./commandstext.html","Text Compare Commands","Text Compare Commands Following is a description of the Text Compare commands, in addition to the common commands . Most of these commands are ava...",""],
["./commandstextedit.html","Text Edit Commands","Text Edit Commands Following is a description of the Text Edit commands, in addition to the common commands . Most of these commands are available...",""],
["./commandstextmerge.html","Text Merge Commands","Text Merge Commands Following is a description of the Text Merge commands, in addition to the common commands . Most of these commands are availab...",""],
["./commandstextpatch.html","Text Patch Commands","Text Patch Commands Following is a description of the Text Patch commands, in addition to the common commands . Most of these commands are availab...",""],
["./commandsver.html","Version Compare Commands","Version Compare Commands Following is a description of the Version Compare commands, in addition to the common commands . Most of these commands a...",""],
["./commands_reference.html","Commands Reference","Commands Reference This part of the documentation describes the commands available in menus and on the toolbar for each view type. Commands that a...",""],
["./command_line_reference.html","Command Line Reference","Command Line Reference Command line executable files Executable Meaning BCompare.exe bcompare This is the main application. Only one copy will run...",""],
["./dir_filtering_the_view.html","Filtering the Folder Compare View","Filtering the Folder Compare View There are three overall type of filters you can use to control a Folder Compare session&#39;s scope: File Filters th...",""],
["./dir_how_to_compare.html","How to Compare in the Folder Compare","How to Compare in the Folder Compare View There are several ways to compare folders and files. If you want a quick look at what has changed betwee...",""],
["./dir_merge_understanding_the_display.html","Understanding the Folder Merge Display","Understanding the Folder Merge Display The Folder Merge display uses color cues to highlight the differences between the base folders. By default,...",""],
["./dir_reconciling_differences.html","Reconciling Differences in the Folder Compare","Reconciling Differences in the Folder Compare View A Folder Compare session provides commands, such as Copy, Move, Delete and Synchronize, to help...",""],
["./dir_sync_how_to_sync.html","How to Sync in the Folder Sync","How to Sync in the Folder Sync View Setting sync parameters In the upper part of the view, specify the Left folder and Right folder involved. Eith...",""],
["./dir_sync_understanding_the_display.html","Understanding the Folder Sync Display","Understanding the Folder Sync Display Sync actions Right file will be copied to the left Left file will be copied to the right Left file will be d...",""],
["./dir_understanding_the_display.html","Understanding the Folder Compare Display","Understanding the Folder Compare Display The Folder Compare display uses color cues to highlight the differences between the two base folders. By ...",""],
["./display_filters.html","Display Filters","Display Filters Display filters limit the view to certain comparison results. For example, you can pick Show Differences to hide all the matching ...",""],
["./dlgbrowsemachine.html","Selecting a Remote Registry","Selecting a Remote Registry If the remote computer you want to connect with does not appear in the list, you may need to do the following: Turn on...",""],
["./dlgdatacolhandling.html","Editing a Column Definition","Editing a Column Definition The Column Handling dialog allows you to set options for each comparison column. A subset of this dialog is used to se...",""],
["./dlgdiralignwithitem.html","Editing an Alignment Override","Editing an Alignment Override Fill in the Align left file (or folder) and with right file (or folder) edits. Mark the Regular expression checkbox ...",""],
["./dlgdirfind.html","Finding Filenames","Finding Filenames Search Find Filename To locate a specific file in a folder view, pick Search Find Filename . Text to find Enter the text to sear...",""],
["./dlgdirotherfilteritem.html","Editing an Other Filter Item","Editing an Other Filter Item To filter by date 1.Pick Older than or Newer than. 2.If the Day(s) ago checkbox is marked, this filter will be the nu...",""],
["./dlgexport.html","Exporting Settings","Exporting Settings Tools Export Settings You can selectively save your program settings, in order to transfer them to another computer, upgrade to...",""],
["./dlgfileformatmanager.html","File Format Management","File Format Management Tools File Formats Pick Tools File Formats to see and manage the entire list of file formats. The order of the list is impo...",""],
["./dlgimport.html","Importing Settings","Importing Settings Tools Import Settings You can import settings that were previously exported from Beyond Compare, even an older version like Bey...",""],
["./dlgnag.html","How to Register","How to Register Step 1 - Try It You can use the program free for 30 days to see if it suits your needs. If you use it beyond 30 days you are oblig...",""],
["./dlgopenwithitem.html","Editing an Open With Item","Editing an Open With Item Enter a name in the Description edit to appear on the Open With menu. To define a keyboard shortcut for the application,...",""],
["./dlgprofilebrowse.html","Browsing Using Profiles","Browsing Using Profiles Session Browse for Folder In general, wherever folders can be used in Beyond Compare, profiles can be used as well. In the...",""],
["./dlgprofilemanager.html","Profile Management","Profile Management Tools Profiles Pick Tools Profiles to see and manage the entire list of profiles. In addition to the named profiles, there is t...",""],
["./dlgprogoptions.html","Program Options","Program Options Tools Options To set program preferences 1.Pick Tools Options to open the Options dialog. 2.In the list at the left, click the ite...",""],
["./dlgregister.html","How to Unlock Beyond Compare","How to Unlock Beyond Compare Help Enter Key Beyond Compare is distributed in evaluation mode, allowing you to see if it suits your needs. Unless y...",""],
["./dlgreport.html","Reports","Reports Comparison reports allow you to save the information from a comparison to view later without re-running the comparison. These reports can ...",""],
["./dlgrestore.html","Restoring Factory Defaults","Restoring Factory Defaults Tools Restore Factory Defaults You can restore settings to their factory defaults. To restore settings 1.Pick Tools Res...",""],
["./dlgsnapshot.html","Saving Snapshots","Saving Snapshots Tools Save Snapshot To save a snapshot 1.Pick Tools Save Snapshot . 2.Enter the path of the folder tree to be saved. If you are c...",""],
["./dlgsourcecontrolmanager.html","Source Control Integration","Source Control Integration Tools Source Control Integration You can associate folders with your SCC-compatible source control application so that ...",""],
["./dlgsupport.html","Reporting Problems","Reporting Problems Help Support If you have found a problem with Beyond Compare, we would like to hear from you! From any top-level window, pick H...",""],
["./dlgtextfindinfiles.html","Finding Text in Files","Finding Text in Files Search Find in Files To locate specific text in multiple files, pick Search Find in Files . Text to find Enter the text to s...",""],
["./dlgtextgrammaritem.html","Editing a Grammar Item","Editing a Grammar Item Pick an existing Element name from the dropdown list or enter your own new name. To define a simple grammar element Pick th...",""],
["./dlgtextreplacementitem.html","Editing a Text Replacement Item","Editing a Text Replacement Item Specify the Text to find and the Replace with text. Mark the Match character case checkbox to only match on text w...",""],
["./dlgworkspacemanager.html","Managing Workspaces","Managing Workspaces Session Load Workspace Manage Workspaces To save your current workspace configuration 1.Pick Session Save Workspace As. 2.Ente...",""],
["./editing_text.html","Editing Text","Editing Text Each pane of the Text Compare view is a full-featured text editor. You can enter and edit text like any other text editor, although a...",""],
["./file_formats.html","File Formats","File Formats Beyond Compare uses file formats to specify how certain types of files are to be handled. For example, files with a .jpg or .png exte...",""],
["./file_masks.html","File Masks","File Masks A file mask is a pattern of characters and wildcards used to match folder and file names. Example: *.* would match any filename. For hi...",""],
["./formatdata.html","Table Format Settings","Table Format Settings Table formats are file formats used by the Table Compare session type. Click the tab containing the settings you want to edi...",""],
["./formatdataconversion.html","Table Format Conversion Settings","Table Format Conversion Settings Table Format Conversion The Conversion tab defines how files should be loaded and saved. Table Compare sessions c...",""],
["./formatdatageneral.html","Table Format General Settings","Table Format General Settings Table Format General The Mask is a set of file types to be associated with this file format. The Description can inc...",""],
["./formatdataregional.html","Table Format Regional Settings","Table Format Regional Settings Table Format Regional Mark the Use system checkbox to use your system&#39;s Regional Settings. Otherwise, pick the Deci...",""],
["./formatdatatype.html","Table Format Type Settings","Table Format Type Settings Table Format Type The Type tab defines the syntax of the data file. Delimited text files Pick Delimited if the fields a...",""],
["./formatexternalgeneral.html","External Format General Settings","External Format General Settings External Format General To compare files using another application, define an external format. The Mask should be...",""],
["./formathex.html","Hex Format Settings","Hex Format Settings Hex formats are file formats used by the Hex Compare session type. Click the tab containing the settings you want to edit: Gen...",""],
["./formathexconversion.html","Hex Format Conversion Settings","Hex Format Conversion Settings Hex Format Conversion The Conversion tab defines how files should be loaded and saved. Pick a Conversion method. Wh...",""],
["./formathexgeneral.html","Hex Format General Settings","Hex Format General Settings Hex Format General The Mask is a set of file types to be associated with this file format. The Description can include...",""],
["./formatpix.html","Picture Format Settings","Picture Format Settings Picture formats are file formats used by the Picture Compare session type. Click the tab containing the settings you want ...",""],
["./formatpixconversion.html","Picture Format Conversion Settings","Picture Format Conversion Settings Picture Format Conversion The Conversion tab defines how files should be loaded. Pick a Conversion method. When...",""],
["./formatpixgeneral.html","Picture Format General Settings","Picture Format General Settings Picture Format General The Mask is a set of file types to be associated with this file format. The Description can...",""],
["./formattext.html","Text Format Settings","Text Format Settings Text formats are file formats used by the Text Compare and Text Merge session types. Click the tab containing the settings yo...",""],
["./formattextconversion.html","Text Format Conversion Settings","Text Format Conversion Settings Text Format Conversion The Conversion tab defines how files should be loaded and saved. Text Compare sessions can ...",""],
["./formattextgeneral.html","Text Format General Settings","Text Format General Settings Text Format General The Mask is a set of file types to be associated with this file format. The Description can inclu...",""],
["./formattextgrammar.html","Text Format Grammar Settings","Text Format Grammar Settings Text Format Grammar The Grammar tab defines the syntax of a file. Grammar elements such as comments and keywords are ...",""],
["./formattextmisc.html","Text Format Miscellaneous Settings","Text Format Miscellaneous Settings Text Format Misc Insert spaces instead of tabs When unmarked, pressing the Tab key inserts a tab character into...",""],
["./glossary.html","Glossary","Glossary Base folder The top-most folder on either side of a folder view. Base folder names appear in the toolbar path edits above each pane of th...",""],
["./grammars.html","Grammars","Grammars A file format specification can include a grammar definition, used for syntax highlighting, and to help define which differences are impo...",""],
["./license_agreement.html","License Agreement","License Agreement Help About Beyond Compare License Your use of Beyond Compare is governed by the following Terms and Conditions: Acceptance of Li...",""],
["./license_agreement_7-zip.html","License Agreement: 7-Zip","7-Zip License for use and distribution 7-Zip Copyright (C) 1999-2010 Igor Pavlov. Licenses for files are: 1) 7z.dll: GNU LGPL + unRAR restriction ...",""],
["./license_agreement_fpc.html","License Agreement: FPC","FPC LICENSE This is the file COPYING.FPC, it applies to the Free Pascal Run-Time Library (RTL) and packages (packages) distributed by members of t...",""],
["./license_agreement_gpl3.html","License Agreement: GPL3","GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007 Copyright &#169; 2007 Free Software Foundation, Inc. Everyone is permitted to copy and distribute ve...",""],
["./license_agreement_htmlviewer.html","License Agreement: HtmlViewer","HtmlViewer License Copyright (c) 1995 - 2008 by L. David Baldwin Copyright (c) 1995 - 2008 by Anders Melander (DitherUnit.pas) Copyright (c) 1995 ...",""],
["./license_agreement_httpget.html","License Agreement: HTTPGet","HTTPGet License This software is provided &#39;as-is&#39;, without any express or implied warranty. In no event will the author be held liable for any dam...",""],
["./license_agreement_innosetup.html","License Agreement: InnoSetup","Inno Setup License Except where otherwise noted, all of the documentation and software included in the Inno Setup package is copyrighted by Jordan...",""],
["./license_agreement_intlck64.html","License Agreement: IntLck64","IntLck64 License Copyright (C) 2005 Will DeWitt Jr. This software is provided &#39;as-is&#39;, without any express or implied warranty. In no event will t...",""],
["./license_agreement_lgpl.html","License Agreement: LGPL","GNU LIBRARY GENERAL PUBLIC LICENSE Version 2, June 1991 Copyright (C) 1991 Free Software Foundation, Inc. 51 Franklin St, Fifth Floor, Boston, MA ...",""],
["./license_agreement_mpl.html","License Agreement: MPL","Mozilla Public License Version 2.0 1. Definitions 1.1. \"Contributor\" means each individual or legal entity that creates, contributes to the creati...",""],
["./license_agreement_pcre.html","License Agreement: PCRE","PCRE License PCRE is a library of functions to support regular expressions whose syntax and semantics are as close as possible to those of the Per...",""],
["./license_agreement_regexpr.html","License Agreement: RegExpr","RegExpr License Author: Andrey V. Sorokin St-Petersburg Russia anso@mail.ru , anso@usa.net http://anso.da.ru http://anso.virtualave.net This libra...",""],
["./license_agreement_textdiff.html","License Agreement: TextDiff","TextDiff License Author: Angus Johnson - angusj-AT-myrealbox-DOT-com Copyright: &#169; 2001-2005 Angus Johnson Licence to use, terms and conditions The...",""],
["./license_agreement_wavpack.html","License Agreement: WavPack","WavPack License Copyright (c) 1998 - 2009 Conifer Software All rights reserved. Redistribution and use in source and binary forms, with or without...",""],
["./license_agreement_wix.html","License Agreement: WiX","WiX License Copyright (c) 2004, Outercurve Foundation. This software is released under the Microsoft Reciprocal License (MS-RL) (the \"License\"); y...",""],
["./license_agreement_zlib.html","License Agreement: Zlib","Zlib License zlib.h -- interface of the &#39;zlib&#39; general purpose compression library version 1.2.3, July 18th, 2005 Copyright (C) 1995-2005 Jean-lou...",""],
["./managing_sessions.html","Managing Sessions","Managing Sessions Beyond Compare automatically saves your most recent sessions so you can come back to them easily. If you want to retain a sessio...",""],
["./moving_bc_to_another_computer.html","Moving Beyond Compare to Another Computer","Moving Beyond Compare to Another Computer To copy or move Beyond Compare to a different computer 1.On the new computer, download and install the l...",""],
["./opattrib.html","Attributes","Attributes Actions Attributes In the Actions menu, the Attributes command modifies various operating system attributes of the selected files and f...",""],
["./opcompare.html","Content Comparisons","Content Comparisons Actions Compare Contents In the Actions menu, the Compare Contents command performs content comparisons on the selected pairs ...",""],
["./opcopy.html","Copy","Copy Actions Copy to Right / Copy to Left / Copy to Side In the Actions menu, the Copy to Right, Copy to Left and Copy to Side commands copy the s...",""],
["./opcopyto.html","Copy to Folder","Copy to Folder Actions Copy to Folder In the Actions menu, the Copy to Folder command copies the selected files and folders to a given folder, opt...",""],
["./opcopytooutput.html","Copy to Output","Copy to Output Actions Copy to Output In the Actions menu, the Copy to Output command copies the selected files and folders to the output side. If...",""],
["./opdelete.html","Delete","Delete Actions Delete In the Actions menu, the Delete command deletes the selected files and folders from one or both sides of the comparison. If ...",""],
["./opexchange.html","Exchange","Exchange Actions Exchange In the Actions menu, the Exchange command moves the selected files and folders from one side of the view to the other. I...",""],
["./opexclude.html","Exclude","Exclude Actions Exclude In the Actions menu, the Exclude command filters out the selected files and folders from the current session. It is a hand...",""],
["./opmerge.html","Merge","Merge Actions Merge In the Actions menu, the Merge command performs a merge of the selected files and folders. If a folder is selected, only its f...",""],
["./opmove.html","Move","Move Actions Move to Right / Move to Left / Move to Side In the Actions menu, the Move to Right, Move to Left and Move to Side commands move the s...",""],
["./opmoveto.html","Move to Folder","Move to Folder Actions Move to Folder In the Actions menu, the Move to Folder command moves the selected files and folders to a given folder, opti...",""],
["./opnewfolder.html","New Folder","New Folder Actions New Folder In the Actions menu, the New Folder command lets you create a folder at the current position. If you have a file or ...",""],
["./oprename.html","Rename","Rename Actions Rename In the Actions menu, the Rename command renames the selected files and folders. In the Action subsection, you can pick eithe...",""],
["./opsync.html","Synchronize","Synchronize Actions Synchronize Update Right / Update Left / Update Both / Mirror to Right / Mirror to Left In the Actions menu, the Synchronize s...",""],
["./optionsarchive.html","Archive Type Options","Archive Type Options Tools Options Archive Types Specify the file types to be associated with each of the supported archive formats. Pick a format...",""],
["./optionsbackup.html","Backup Options","Backup Options Tools Options Backups Beyond Compare can create a backup of your files before overwriting them during a copy or move operation, or ...",""],
["./optionscolor.html","Color, Font Options","Color, Font Options Tools Options Colors, Fonts Click the item containing the options you want to set: Folder Views File Views Picture Compare ",""],
["./optionscommand.html","Toolbar, Shortcut, Menu Options","Toolbar, Shortcut, Menu Options Tools Options Toolbars, etc. These options allow you to control which commands appear in menus and on toolbars, an...",""],
["./optionsdircolor.html","Folder View Color, Font Options","Folder View Color, Font Options Tools Options Colors, Fonts Folder Views These options allow you to customize overall colors and fonts used in fol...",""],
["./optionsfilecolor.html","File View Color, Font Options","File View Color, Font Options Tools Options Colors, Fonts File Views These options allow you to customize visual aspects of the various types of f...",""],
["./optionsnextdiff.html","Next Difference Options","Next Difference Options Tools Options Next Difference Set these options to reflect your preferences concerning how to peruse differences. When loa...",""],
["./optionsop.html","File Operation Options","File Operation Options Tools Options File Operations Confirmations By default, Beyond Compare prompts for confirmation before performing various a...",""],
["./optionsopenwith.html","\"Open With\" Application Options","\"Open With\" Application Options Tools Options Open With You can configure external applications to appear in the Open With submenu. Click the New ...",""],
["./optionspixcolor.html","Picture Compare Color Options","Picture Compare Color Options Tools Options Colors, Fonts Picture Compare These options allow you to customize colors used in Picture Compare view...",""],
["./optionsstartup.html","Startup Options","Startup Options Tools Options Startup Startup options When Beyond Compare starts up, it normally shows the Home view. To have the program automati...",""],
["./optionstab.html","Tab Options","Tab Options Tools Options Tabs When working with multiple sessions simultaneously, Beyond Compare can open them in independent windows, or under t...",""],
["./optionstext.html","Text Editing Options","Text Editing Options Tools Options Text Editing These options apply to Text Compare and Text Merge sessions. Auto indent When marked and a new lin...",""],
["./optionstweak.html","Tweak Options","Tweak Options Tools Options Tweaks Tweaks are advanced or obscure program options that we group here to avoid cluttering other areas. Check for Up...",""],
["./optouch.html","Touch","Touch Actions Touch In the Actions menu, the Touch command modifies the timestamp (date/time last modified) of the selected files. If Copy timesta...",""],
["./pix_how_to_compare.html","How to Compare in the Picture Compare","How to Compare in the Picture Compare View Aligning image content You can compare images that have been resized, rotated, reflected or cropped. Pi...",""],
["./profileamazons3.html","Amazon S3 Profile Settings","Amazon S3 Profile Settings Amazon S3 Profile General Authentication type Controls where credentials are loaded from. Saved S3 credentials Use save...",""],
["./profiledropbox.html","Dropbox Profile Settings","Dropbox Profile Settings Dropbox Profile General The Description can include any text you want. ",""],
["./profileftp.html","FTP Profile Settings","FTP Profile Settings Click the tab for the settings you wish to edit: Global Login Server Connection Proxy Listing Transfer ",""],
["./profileftpconnection.html","FTP Profile Connection Settings","FTP Profile Connection Settings FTP Profile Connection These settings control how the connection is made to the remote server. Simultaneous connec...",""],
["./profileftpglobal.html","FTP Profile Global Settings","FTP Profile Global Settings FTP Default Profile Global Anonymous logins Email address When connecting to anonymous FTP sites, it is customary to i...",""],
["./profileftplisting.html","FTP Profile Listing Settings","FTP Profile Listing Settings FTP Profile Listings Beyond Compare parses the plain text directory listings sent from the FTP server in order to det...",""],
["./profileftplogin.html","FTP Profile Login Settings","FTP Profile Login Settings FTP Profile Login Protocol Specify FTP or one of the secure FTP options: SSL or SSH. Port Override if you don&#39;t want to...",""],
["./profileftpproxy.html","FTP Profile Proxy Settings","FTP Profile Proxy Settings FTP Profile Proxy Use proxy Mark if connections should use FTP Proxy protocol. If you are not on a Local Area Network (...",""],
["./profileftpserver.html","FTP Profile Server Settings","FTP Profile Server Settings FTP Profile Server Filenames are case sensitive Mark to require filename character case to be the same in order to lin...",""],
["./profileftptransfer.html","FTP Profile Transfer Settings","FTP Profile Transfer Settings FTP Profile Transfer These settings control how files are transferred to and from the FTP server. Transfer type FTP ...",""],
["./profileonedrive.html","OneDrive Profile Settings","OneDrive Profile Settings OneDrive Profile General The Description can include any text you want. ",""],
["./profilesvn.html","Subversion Profile Settings","Subversion Profile Settings Subversion Profile General URL of repository, Revision Specify parameters for your account. The Description can includ...",""],
["./profilewebdav.html","WebDAV Profile Settings","WebDAV Profile Settings WebDAV Profile General URL, Username, Password, Recursive listings Specify parameters for your account. The Description ca...",""],
["./regular_expression_reference.html","Regular Expression Reference","Regular Expression Reference Regular Expressions are a powerful way to define patterns for searching and matching. Beyond Compare allows you to us...",""],
["./remote_services.html","Remote Services","Remote Services Remote services include FTP and Subversion. FTP sites are represented using the standard syntax: ftp://username@ftp.hostname.com f...",""],
["./rules_vs_file_formats.html","Rules vs. File Formats","Rules vs. File Formats In Beyond Compare, file formats describe the syntax of specific kinds of files by defining elements. File formats are typic...",""],
["./sample_regular_expressions.html","Sample Regular Expressions","Sample Regular Expressions Expression Meaning ^abc Match \"abc\" at beginning of line abc$ Match \"abc\" at end of line ^abc$ Match the line \"abc\" exa...",""],
["./sample_scripts.html","Sample Scripts","Sample Scripts The following are some sample scripts to show how Beyond Compare can use scripts. You can either use these scripts as is or model y...",""],
["./scheduling_a_script.html","Scheduling a Script","Scheduling a Script You can use Beyond Compare&#39;s script processor to perform certain tasks, such as synchronizing folders, without interaction. Fo...",""],
["./scripting_reference.html","Scripting Reference","Scripting Reference A script is a simple text file containing a list of commands which can control the program and automatically perform file oper...",""],
["./scripts.html","Scripts","Scripts Beyond Compare provides a script processing feature which allows you to automate routine tasks. A script is a simple text file containing ...",""],
["./searching_for_text.html","Searching for Text","Searching for Text To search for text in a Text Compare session, pick Search Find . Type the text or a regular expression pattern in the edit, or ...",""],
["./sessiondata.html","Table Compare Settings","Table Compare Settings Session Session Settings Click the tab containing the settings you want to edit: Specs Format Columns Alignment ",""],
["./sessiondataalignment.html","Table Compare Alignment Settings","Table Compare Alignment Settings Session Session Settings Alignment The Alignment tab settings control the algorithm for aligning rows in the comp...",""],
["./sessiondatacolumns.html","Table Compare Column Settings","Table Compare Column Settings Session Session Settings Columns Each line in the display represents a comparison column, and shows: Comparison if k...",""],
["./sessiondataformats.html","Table Compare File Format Settings","Table Compare File Format Settings Session Session Settings Format Specify the file format to be used when reading the left and/or right files. Th...",""],
["./sessiondataspecs.html","Table Compare Spec Settings","Table Compare Spec Settings Session Session Settings Specs Specify the files to be compared. Mark Disable editing to protect content from being ch...",""],
["./sessiondir.html","Folder Compare Settings","Folder Compare Settings Session Session Settings Click the tab containing the settings you want to edit: Specs Comparison Handling Name Filters Ot...",""],
["./sessiondircomparison.html","Folder Compare Comparison Settings","Folder Compare Comparison Settings Session Session Settings Comparison These settings control what is considered a difference in a folder session....",""],
["./sessiondirhandling.html","Folder Compare Handling Settings","Folder Compare Handling Settings Session Session Settings Handling Folder handling Automatically scan subfolders in background causes folders to b...",""],
["./sessiondirmerge.html","Folder Merge Settings","Folder Merge Settings Session Session Settings Click the tab containing the settings you want to edit: Specs Comparison Handling Name Filters Othe...",""],
["./sessiondirmergecomparison.html","Folder Merge Comparison Settings","Folder Merge Comparison Settings Session Session Settings Comparison These settings control what is considered a difference in a folder session. Q...",""],
["./sessiondirmergehandling.html","Folder Merge Handling Settings","Folder Merge Handling Settings Session Session Settings Handling Folder handling Automatically scan subfolders in background causes folders to be ...",""],
["./sessiondirmergemisc.html","Folder Merge Miscellaneous Settings","Folder Merge Miscellaneous Settings Session Session Settings Misc To override file format associations The Enabled file formats list lets you over...",""],
["./sessiondirmergenamefilter.html","Folder Merge Name Filter Settings","Folder Merge Name Filter Settings Session Session Settings Name Filters You can include or exclude folders and files based on their names by using...",""],
["./sessiondirmergeotherfilters.html","Folder Merge Other Filter Settings","Folder Merge Other Filter Settings Session Session Settings Other Filters You can exclude files from a folder session based on criteria other than...",""],
["./sessiondirmergespecs.html","Folder Merge Spec Settings","Folder Merge Spec Settings Session Session Settings Specs Specify the base folders to be merged. Merge to defines the destination folder of the me...",""],
["./sessiondirmisc.html","Folder Compare Miscellaneous Settings","Folder Compare Miscellaneous Settings Session Session Settings Misc To force a different alignment By default, a folder session aligns files and s...",""],
["./sessiondirnamefilter.html","Folder Compare Name Filter Settings","Folder Compare Name Filter Settings Session Session Settings Name Filters You can include or exclude folders and files based on their names by usi...",""],
["./sessiondirotherfilters.html","Folder Compare Other Filter Settings","Folder Compare Other Filter Settings Session Session Settings Other Filters You can exclude files from a folder session based on criteria other th...",""],
["./sessiondirspecs.html","Folder Compare Spec Settings","Folder Compare Spec Settings Session Session Settings Specs Specify the base folders to be compared. Mark Disable editing to protect content from ...",""],
["./sessiondirsync.html","Folder Sync Settings","Folder Sync Settings Session Session Settings Click the tab containing the settings you want to edit: Specs Sync Comparison Handling Name Filters ...",""],
["./sessiondirsynccomparison.html","Folder Sync Comparison Settings","Folder Sync Comparison Settings Session Session Settings Comparison These settings control what is considered a difference in a folder session. Qu...",""],
["./sessiondirsynchandling.html","Folder Sync Handling Settings","Folder Sync Handling Settings Session Session Settings Handling Folder handling Sync empty folders will affect folders without content or whose en...",""],
["./sessiondirsyncmisc.html","Folder Sync Miscellaneous Settings","Folder Sync Miscellaneous Settings Session Session Settings Misc To force a different alignment By default, a folder session aligns files and subf...",""],
["./sessiondirsyncnamefilter.html","Folder Sync Name Filter Settings","Folder Sync Name Filter Settings Session Session Settings Name Filters You can include or exclude folders and files based on their names by using ...",""],
["./sessiondirsyncops.html","Folder Sync Synchronize Settings","Folder Sync Synchronize Settings Session Session Settings Sync Operations Presets You can use one of the predefined sync methods described in the ...",""],
["./sessiondirsyncotherfilters.html","Folder Sync Other Filter Settings","Folder Sync Other Filter Settings Session Session Settings Other Filters You can exclude files from a folder session based on criteria other than ...",""],
["./sessiondirsyncspecs.html","Folder Sync Spec Settings","Folder Sync Spec Settings Session Session Settings Specs Specify the base folders to be synced. Mark Disable editing to protect content from being...",""],
["./sessionhex.html","Hex Compare Settings","Hex Compare Settings Session Session Settings Click the tab containing the settings you want to edit: Specs Format Comparison ",""],
["./sessionhexcomparison.html","Hex Compare Comparison Settings","Hex Compare Comparison Settings Session Session Settings Comparison These settings control how the files are compared. Complete will align the byt...",""],
["./sessionhexformats.html","Hex Compare File Format Settings","Hex Compare File Format Settings Session Session Settings Format Specify the file format to be used when reading the left and/or right files. The ...",""],
["./sessionhexspecs.html","Hex Compare Spec Settings","Hex Compare Spec Settings Session Session Settings Specs Specify the files to be compared. Mark Disable editing to protect content from being chan...",""],
["./sessionmp3.html","MP3 Compare Settings","MP3 Compare Settings Session Session Settings Click the tab containing the settings you want to edit: Specs Importance ",""],
["./sessionmp3importance.html","MP3 Compare Importance Settings","MP3 Compare Importance Settings Session Session Settings Importance These settings control which differences you consider important. ",""],
["./sessionmp3specs.html","MP3 Compare Spec Settings","MP3 Compare Spec Settings Session Session Settings Specs Specify the files to be compared. The Description can include any text you want. ",""],
["./sessionpix.html","Picture Compare Settings","Picture Compare Settings Session Session Settings Click the tab containing the settings you want to edit: Specs Format Replacements ",""],
["./sessionpixformats.html","Picture Compare File Format Settings","Picture Compare File Format Settings Session Session Settings Format Specify the file format to be used when reading the left and/or right files. ...",""],
["./sessionpixreplacements.html","Picture Compare Replacement Settings","Picture Compare Replacement Settings Session Session Settings Replacements Replacements identify changes that should be considered unimportant. Yo...",""],
["./sessionpixspecs.html","Picture Compare Spec Settings","Picture Compare Spec Settings Session Session Settings Specs Specify the files to be compared. The Description can include any text you want. ",""],
["./sessionreg.html","Registry Compare Settings","Registry Compare Settings Session Session Settings Click the tab containing the settings you want to edit: Specs ",""],
["./sessionregspecs.html","Registry Compare Spec Settings","Registry Compare Spec Settings Session Session Settings Specs Specify the files to be compared. The Description can include any text you want. ",""],
["./sessiontext.html","Text Compare Settings","Text Compare Settings Session Session Settings Click the tab containing the settings you want to edit: Specs Format Importance Alignment Replaceme...",""],
["./sessiontextalignment.html","Text Compare Alignment Settings","Text Compare Alignment Settings Session Session Settings Alignment The Alignment tab settings control the algorithm for aligning lines in the comp...",""],
["./sessiontextformats.html","Text Compare File Format Settings","Text Compare File Format Settings Session Session Settings Format Specify the file format to be used when reading the left and/or right files. The...",""],
["./sessiontextimportance.html","Text Compare Importance Settings","Text Compare Importance Settings Session Session Settings Importance These settings control which differences you consider important in the curren...",""],
["./sessiontextmerge.html","Text Merge Settings","Text Merge Settings Session Session Settings Click the tab containing the settings you want to edit: Specs Format Importance Alignment ",""],
["./sessiontextmergealignment.html","Text Merge Alignment Settings","Text Merge Alignment Settings Session Session Settings Alignment The Alignment tab settings control the algorithm for aligning lines in the compar...",""],
["./sessiontextmergeformats.html","Text Merge File Format Settings","Text Merge File Format Settings Session Session Settings Format Specify the file format to be used when reading the input files. The default selec...",""],
["./sessiontextmergeimportance.html","Text Merge Importance Settings","Text Merge Importance Settings Session Session Settings Importance These settings control which differences you consider important in the current ...",""],
["./sessiontextmergespecs.html","Text Merge Spec Settings","Text Merge Spec Settings Session Session Settings Specs Specify the files to be merged. Merge to defines the destination file of the merge results...",""],
["./sessiontextreplacements.html","Text Compare Replacement Settings","Text Compare Replacement Settings Session Session Settings Replacements Replacements identify repetitive changes that should be considered unimpor...",""],
["./sessiontextspecs.html","Text Compare Spec Settings","Text Compare Spec Settings Session Session Settings Specs Specify the files to be compared. Mark Disable editing to protect content from being cha...",""],
["./sessionver.html","Version Compare Settings","Version Compare Settings Session Session Settings Click the tab containing the settings you want to edit: Specs Importance ",""],
["./sessionverimportance.html","Version Compare Importance Settings","Version Compare Importance Settings Session Session Settings Importance These settings control which differences you consider important. ",""],
["./sessionverspecs.html","Version Compare Spec Settings","Version Compare Spec Settings Session Session Settings Specs Specify the files to be compared. The Description can include any text you want. ",""],
["./session_settings.html","Session Settings","Session Settings To edit session settings 1.Pick Session Session Settings . 2.Modify the desired settings on each tab. 3.The dropdown list at the ...",""],
["./settings_reference.html","Settings Reference","Settings Reference Beyond Compare is highly configurable, and it sometimes can be hard to know where to go in the program to change a specific set...",""],
["./sharing_sessions.html","Sharing Sessions","Sharing Sessions Multiple users can share sessions by using a shared sessions file. To create a shared sessions file 1.Pick Tools Export Settings ...",""],
["./snapshots.html","Snapshots","Snapshots In the Tools menu, the Save Snapshot command saves a compressed read-only listing of the specified folder and all of its subfolders, inc...",""],
["./specs.html","Specs","Specs A Spec is the name of a folder or file. Beyond Compare supports several different types of specs. Local and network drives are represented u...",""],
["./standard_vs_pro.html","Standard vs Pro Editions","Standard vs. Pro Editions The Standard edition of Beyond Compare is a powerful full-featured comparison tool, not a stripped-down \"lite\" version. ...",""],
["./support_ordering_and_license.html","Support, Ordering and License","Support, Ordering and License For the latest version of Beyond Compare and for other news about the program, visit our web site at: www.scootersof...",""],
["./using_bc.html","Using Beyond Compare","Using Beyond Compare Beyond Compare handles a wide variety of comparison tasks. It has specialized views for different kinds of files and differen...",""],
["./using_text_merge.html","Using Text Merge","Using Text Merge Once Beyond Compare has completed the comparison it will show up to four panes: The left, center, and right panes at the top, wit...",""],
["./viewdata.html","Table Compare Overview","Table Compare Overview A Table Compare session compares text files containing tabular data, such as .csv (comma separated values) files, in a side...",""],
["./viewdir.html","Folder Compare Overview","Folder Compare Overview A Folder Compare session compares two folder structures side-by-side, in a variation of the familiar Windows Explorer styl...",""],
["./viewdirmerge.html","Folder Merge Overview","Folder Merge Overview A Folder Merge session displays two or three folder structures side-by-side. The left and right panes hold two versions of a...",""],
["./viewdirsync.html","Folder Sync Overview","Folder Sync Overview A Folder Sync session is a specialized folder session that synchronizes folders by copying or deleting files. Once you set up...",""],
["./viewhex.html","Hex Compare Overview","Hex Compare Overview A Hex Compare session visually compares the raw content of two files, either in a side-by-side or over-under layout. It displ...",""],
["./viewhome.html","Home View","Home View Overview When you open a new window or tab, Beyond Compare displays the Home view: From the Home view, you can: Start a new comparison s...",""],
["./viewother.html","Other View Types","Other View Types MP3 Compare An MP3 Compare session compares two MP3 files with differences in tag fields highlighted. See also MP3 Compare Comman...",""],
["./viewpix.html","Picture Compare Overview","Picture Compare Overview A Picture Compare session compares a pair of image files visually, showing the differences between them. Supported image ...",""],
["./viewreg.html","Registry Compare Overview","Registry Compare Overview A Registry Compare session compares live registries on your computer or other computers on your network, and .reg export...",""],
["./viewtext.html","Text Compare Overview","Text Compare Overview A Text Compare session visually compares two text files, in a side-by-side or over-under layout. It helps you analyze and re...",""],
["./viewtextedit.html","Text Edit Overview","Text Edit Overview A Text Edit view is a single-pane text editor. See also Text Edit Commands Text Format Settings Text Editing Options ",""],
["./viewtextmerge.html","Text Merge Overview","Text Merge Overview A Text Merge session contains two or three non-editable source panes and an editable output pane. The left and right panes hol...",""],
["./viewtextpatch.html","Text Patch Overview","Text Patch Overview A Text Patch view recreates a comparison represented in a patch file. Patch files can be generated using a Text Compare report...",""],
["./walking_through_differences.html","Walking Through Differences","Walking Through Differences In the Search menu, the Next Difference Section and Previous Difference Section commands help you step through all the...",""],
["./welcome.html","Welcome","Welcome to Beyond Compare 4 Beyond Compare is a utility for comparing files and folders. It can help you find and reconcile differences in source ...",""],
["./whats_new.html","What&#39;s New","What&#39;s New Here are some of the significant new features in Beyond Compare 4. Items flagged with are only available in the Pro edition. Mac versio...",""],
["./where_settings_are_stored.html","Where Settings are Stored on your Computer","Where Settings are Stored on your Computer Beyond Compare stores your sessions, customized file formats and other preferences as .xml files in its...",""]];
