#!/bin/sh

add=$(/usr/bin/curl -s cip.cc|grep -o "中国")
if [ x"$add" = x"中国" ];then
	url="https://coding.net/u/lihaoyun6/p/macOS-Displays-icon/git/raw/master"
else
	url="https://raw.githubusercontent.com/lihaoyun6/macOS-Displays-icon/master"
fi

/usr/bin/curl -s ${url}/MonitorFace.sh|/bin/sh